version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
            options:
                max-size: 10m
                max-file: "3"

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
            options:
                max-size: 10m
                max-file: "3"
    volumes:
      # - ./examples/intro-example/dags:/usr/local/airflow/dags
      - .:/usr/local/airflow/dags
      #- ./airflow-data/includes:/opt/airflow/includes
      #- ./airflow-data/logs:/opt/airflow/logs
      #- ./airflow-data/plugins:/opt/airflow/plugins
      #- ./airflow-data/airflow.cfg:/opt/airflow/airflow.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3